name: appmable_desktop
description: AppMable Desktop
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ^3.3.2

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^5.0.1
  flutter_datetime_picker_plus: ^2.1.0
  freezed_annotation:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.6.4
  get_storage:
  injectable: ^2.3.2
  intl: ^0.18.1
  http: ^0.13.5
  # encrypt
  encrypt: ^5.0.1
  pointycastle: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  test:
  faker: ^2.0.0
  mockito: ^5.3.2

  build_runner:
  injectable_generator: ^2.4.1

  very_good_analysis: ^5.1.0
  dart_code_metrics: ^5.7.6

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/certificates/
