name: appmable_desktop
description: AppMable Desktop
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ^3.3.2

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^2.3.9
  freezed_annotation:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: 7.2.0
  get_storage:
  injectable: 1.5.3
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  test:
  faker: ^2.0.0
  mockito: ^5.3.2

  build_runner:
  injectable_generator: 1.5.4

  very_good_analysis: ^3.1.0
  dart_code_metrics: ^4.19.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
